version: '3.9'

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: products
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - 6379:6379

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - redis
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/products
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./product-service:/app
    restart: unless-stopped

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - 5001:5001
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/auth
      - JWT_SECRET=supersecretkey_change_me_in_prod
    volumes:
      - ./auth-service:/app
    restart: unless-stopped

volumes:
  mongo-data:
